### ISSUE TITLE
Breaking changes between 12.5.0 and 12.8.2 in CSS?

### ISSUE THREAD

**Issue by chester23491** [baloise-incubator/design-system#1202]
Hello

When upgrading to the latests version `12.8.2`, we are facing CSS issues. The element `<p>` got the new `font-size` parameter and thus overrides prior CSS class assignments from baloise components like `bal-text`.

```tsx
<BalText className="is-size-display">Test</BalText>
```
Before update:
![image](https://user-images.githubusercontent.com/22290769/223175879-bc799cd3-f910-40c5-9e1e-e60787ea9ca1.png)

After update:
![image](https://user-images.githubusercontent.com/22290769/223176947-8aa077d9-b161-456c-a315-86fb2c69d11a.png)

**Comment by hirsch88** [comment]
Hi @chester23491 

The bal-text component has a prop called size. Please use that. Otherwise you need to use the bar-heading. Never use css classes on components like that to overwrite styles. this is very dangerous and not recommended at all.

Component API
https://baloise-design-system.vercel.app/?path=/docs/components-text--basic#component-api

Typography
https://baloise-design-system.vercel.app/?path=/docs/foundation-typography-overview--page
