### ISSUE TITLE
bal-select has no fallback to react for form reset

### ISSUE THREAD

**Issue by hirsch88** [baloise-incubator/design-system#197]
Issue from => https://github.com/baloise/design-system/issues/641
Openedby => @Sw0rdiX

## Detailed description

> Describe in detail the issue you're having.
- If u reset a Form, the default value for bal-select will not be selected anymore...

> What did you expect to happen? What happened instead? What would you like to see changed?
- If i reset a Form, the value which is put in the bal-select as selected value will be selected again. 

> What browser are you working in?
- Chrome

## Steps to reproduce the issue

![image](https://user-images.githubusercontent.com/3681337/177402590-1f70f160-8111-4b9a-a911-7fbed9eac52c.png)

1. select another value as selected
2. reset form 

## Additional information

- Screenshots of Working Code
![image](https://user-images.githubusercontent.com/3681337/177402395-5676b550-1712-4ece-82dd-4255ae786b63.png)

**Comment by Sw0rdiX** [comment]
@hirsch88, in our understanding a reset to the selected value at the beginning of choice would be the right way. 
https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_select
for us the native select is not implemented right here

now the placeholder is shown, but i think placeholder is just the right value if no value is selected before. this is in point also not native because placeholder not exist in select field.
