### ISSUE TITLE
bal-modal backdrop color/opacity customisable

### ISSUE THREAD

**Issue by JasperDeLanghe** [baloise-incubator/design-system#290]
### Summary

On the bal-modal component we would like to see a property to customise the backdrop color. 
Right now it's set to the primary brand color (#000d6e) with 0.8 opacity.

### Justification

Business found that the use of modals in our lead generation apps is good but the backdrop is a little too dark.
They would like to see it lighter.

### Must-have functionality

Additional property to customise either the entire color of the backdrop but this might not be desired from a design standpoint.
So maybe a property to allow different opacity levels of the primary brand color?

### Specific timeline issues / requests

Not specified.

### Available extra resources

I can look into scheduling time to contribute this myself in our upcoming sprint (starting 11/08) if that would help.

**Comment by Gagne87** [comment]
@clastzoo I prepared a quick comparison matrix [here](https://www.figma.com/file/lgDn2QZqoJJlYzGTe6cOmr/%F0%9F%A7%A9-Components?node-id=1643%3A9318) in order to grasp better the alternatives we have. 

**My proposal for this one:** 

- Find a global solution for consistency reasons (proposing different opacities will lead to different user experience)
- In order to find a compromise I would suggest to set the opacity to 0.6 (as I agree that 0.8 might be a little too dark)

Let me know what you think.

**Comment by hirsch88** [comment]
moved to https://github.com/baloise/design-system/issues/718
