### ISSUE TITLE
Implementation for animated links

### ISSUE THREAD

**Issue by janineKleessen** [baloise-incubator/design-system#358]
Links with underline should have a hovereffect.
Animation is described on figma and in jiraticket [BARE-396](https://jira.ibmix.de/browse/BARE-396)

@clastzoo Gery and me checkt animation but it is not clear , please contact meta for correct implementation

https://user-images.githubusercontent.com/62377419/188448200-f3ab0740-9fd5-433f-a962-b4ba0cfb6d76.mov

**Comment by clastzoo** [comment]
@clastzoo add link for css animation here

**Comment by nobilo** [comment]
We can make animated-link class and put it in button section, and see how it looks

**Comment by clastzoo** [comment]
Hi @nobilo 

I would have the following request:

- Please add only one pixel to the bottom line instead of two.
- Is it possible to use this custom bezier curve? `0.58, 0.77, 0.07, 0.97`
- Can you please preview also the negative version on a colored background? 

Could you please use this example to create an inline version of the animated link?:

Kommt eine Fluggesellschaft Ihren rechtmässigen Ansprüchen nicht oder nur teilweise nach, können Sie sich an die zuständige Aufsichtsbehörde wenden. In der Schweiz nimmt das [Bundesamt für Zivilluftfahrt](https://www.bazl.admin.ch/bazl/de/home/passagiere/fluggastrechte.html). Ihre Anzeige entgegen und leitet gegebenenfalls ein Verfahren gegen die Fluggesellschaft ein. Auch im Rahmen Ihrer Rechtsschutzversicherung erhalten Sie über den Privatrechtsschutz Hilfe und Unterstützung bei rechtlichen Belangen hinsichtlich Ihrer Forderungen aufgrund von Annullierung, Verspätung oder Überbuchung. Oder Sie machen sich die Dienste von Onlineportalen, beispielsweise [cancelled.ch](http://cancelled.ch/), zunutze. Gegen eine Gebühr kümmern sich diese um Ihr Anliegen. Der Vorteil: Die Portale kennen sämtliche Regeln, um Ihre Ansprüche zeitnah und korrekt durchzusetzen.

cc @Gagne87

**Comment by nobilo** [comment]
we are going to copy from twitter, use colors from existing link: default color, hover color, active color

**Comment by clastzoo** [comment]
we will close this ticket and open a new one.

https://github.com/baloise-incubator/design-system/issues/512
