### ISSUE TITLE
[bal-badge] Extend color prop options

### ISSUE THREAD

**Issue by JasperDeLanghe** [baloise-incubator/design-system#440]
### Summary

We would like to have more options available in the color property of the bal-badge.
For example, in a specific project we would l like to use the color "red-3" as the bal-badge background color.

Only asking for development.

### Justification

N/A

### Desired UX and success metrics

N/A

### Specific timeline issues / requests

N/A

**Comment by hirsch88** [comment]
@Gagne87 could you check if the color red-3 is fine for default?

**Comment by Gagne87** [comment]
@hirsch88 @JasperDeLanghe from my perspective. If we would allow "red-3" we would also have to allow "green-3" etc. in order to be consistent with that. For me the important thing is that the accessibility will not be influenced.

@JasperDeLanghe could you maybe post the concrete use-case where this would be needed? Thanks, Laurent

**Comment by Gagne87** [comment]
[Link to Figma](https://www.figma.com/file/WMCzHqFzaeFEOAiAhVWqR8/Customer-zone-UI---Navigation-%26-footer?node-id=769%3A10961) 


![Image](https://user-images.githubusercontent.com/29020214/190596501-1f3f6af8-7417-4f76-9d5b-0fe316285f2d.png)

**Comment by Gagne87** [comment]
Created technical issue for that one. #537

**Comment by hirsch88** [comment]
move to https://github.com/baloise/design-system/issues/719
