### ISSUE TITLE
[bal-button]: text in mobile view is not centered

### ISSUE THREAD

**Issue by BerSteve** [baloise-incubator/design-system#477]
## Summary
Should text be centered in this case?

## Relevant information
![text on button not centered](https://user-images.githubusercontent.com/35540320/188888177-e23ce6bc-c495-4c67-a9f4-46e1211a161f.png)

**Comment by hirsch88** [comment]
<img width="377" alt="image" src="https://user-images.githubusercontent.com/6384499/188899506-665d3298-589a-4420-889f-e7a17f55f673.png">

@Gagne87 @clastzoo what about button with icons?

**Comment by hirsch88** [comment]
<img width="404" alt="image" src="https://user-images.githubusercontent.com/6384499/188899642-b0a959b7-7809-4e66-bcce-5b0709cee684.png">

with centre looks strange

**Comment by Gagne87** [comment]
@hirsch88 @mladenplaninicic @clastzoo I just investigated this issue and this is my proposal: 

- text-align: center
- Increase margin-right of the icon from 8 to 12px

Imho the + icon uses a much thiner border than the label and that's why it could still look a little unbalanced. But I think to center the text and increase the margin will help a little.

**Comment by hirsch88** [comment]
duplication #562
