### ISSUE TITLE
[bal-navigation] Meta nav on desktop is not displayed when scrolling upwards

### ISSUE THREAD

**Issue by fabio-tedesco** [baloise-incubator/design-system#743]
## Detailed description

As described here https://jira.ibmix.de/browse/BARE-1007 we have an issue on our side: when scrolling upwards the meta nav doesn't show up. 

## Steps to reproduce the issue

1. Tried to reproduce it on storybook without success
2. On our side 'isOverViewportBottom' is always true

## Additional information

- Seems like on our side the calculation 'isOverViewportBottom' - happening in the scroll listener in ds bal-navigation - **is always true**, hiding the meta nav, except when the page is at the top. While on Storybook its value switches between true and false, the latter case shows the meta when scrolling updwards on storybook. Removing that const 'isOverViewportBottom' and its check resolves the issue.

**Comment by hirsch88** [comment]
@fabio-tedesco we cannot remove that, because that is needed for iOS devices / safari

**Comment by hirsch88** [comment]
@fabio-tedesco do you have a link for us to reproduce?

**Comment by fabio-tedesco** [comment]
@hirsch88 here  https://baloise-reb.dev.aperto.systems/baloise-qa/de/qa/Sprints/sprint-19/Blog-News-Teaser-Stream.html as described here https://jira.ibmix.de/browse/BARE-1007

**Comment by hirsch88** [comment]
@fabio-tedesco it also appears that the stage position is not correct on your side with this with bar at the top



![Image](https://user-images.githubusercontent.com/6384499/196374227-f4d57564-829c-4f08-8fe7-9d14932c19a0.png)

**Comment by hirsch88** [comment]
@fabio-tedesco what did you do ? :-D



![Image](https://user-images.githubusercontent.com/6384499/196378611-37c3f4ca-0d25-4c6b-8c11-5859ad5175e5.png)



They can not be the same!

The **clientHeight** property returns the viewable height of an element in pixels, including padding, but not the border, scrollbar or margin.

The **scrollHeight** property returns the height of an element including padding, but excluding borders, scrollbars, or margins.

**Comment by fabio-tedesco** [comment]
hi @hirsch88 I didn't do anything. Lets discuss it in the tech daily.

**Comment by fabio-tedesco** [comment]
hi @hirsch88 seems like using the html element to get the clientHeight works as expected. The reason why the body clientHeight is actually the same as the body scrollHeight is actually unknown. 
Using this const declaration should be fine and working in all the cases and testing locally it should works as expected, calculating the max height correctly, also on our side: 
`const maxScrollHeight = document.body.scrollHeight - (document.documentElement.clientHeight || document.body.clientHeight)`

**Comment by Sw0rdiX** [comment]
@hirsch88, in https://design-system-next.vercel.app/iframe.html?args=&id=components-navigation--basic&viewMode=story
the css class `.sb-show-main {
    height: 100vh;
}` restrict the body to the clientHeight of 100vh otherwise the behaviour will be the hole content height of scrollHeight

https://developer.mozilla.org/en-US/docs/Web/API/Element/clientHeight
When clientHeight is used on the root element (the `<html>` element), (or on `<body>` if the document is in **quirks mode**), the viewport's height (excluding any scrollbar) is returned. [This is a special case of clientHeight](https://www.w3.org/TR/2016/WD-cssom-view-1-20160317/#dom-element-clientheight).
body clientHeight is working if quirks mode is on. but we used in both cases the ` <!DOCTYPE html>` so quirks mode is disabled. 

and the hole quirks mode is just a IE Thing :)

the clientHeight is not viewable height it is just the height of element or the restricted height ;-)

in our case we have no 100vh on body tag, this is the difference to the storybook

**Comment by hirsch88** [comment]
@Sw0rdiX how about we set this height: 100vh; to body as well?
