### ISSUE TITLE
[bal-linklist] Additional icon

### ISSUE THREAD

**Issue by clastzoo** [baloise-incubator/design-system#893]
Lets update the check-circle icon with the new one.

![Image](https://user-images.githubusercontent.com/29020214/208877302-93f8692d-93ee-4cd9-a46f-4e11da44c0c3.svg)

-------------------

We need to prove an option to additionally add

- [x] Star Icon Stroke (Default)
- [x] Star Icon Solid

To the linklist as properties.

![Image](https://user-images.githubusercontent.com/62377419/203041868-02fdf48e-8b0c-4791-8da4-1b07560c3cbd.png)

For the Online Quiz we need an option to place an additional icon into the link list. 
Would this be possible currently?

**Comment by hirsch88** [comment]
@fabio-tedesco multiple icons are already supported. Have a look at the below source code.
@clastzoo will create the missing icons for it

```html
<bal-list border>
    <bal-list-item clickable href="www.baloise.com" target="_blank">
        <bal-list-item-icon>
            <bal-icon name="date" size="small"></bal-icon>
        </bal-list-item-icon>
        <bal-list-item-icon>
            <bal-icon name="date" size="small"></bal-icon>
        </bal-list-item-icon>
        <bal-list-item-content>
            <bal-list-item-title>List item with a lot of icons</bal-list-item-title>
        </bal-list-item-content>
        <bal-list-item-icon right>
            <bal-icon name="date" size="small"></bal-icon>
        </bal-list-item-icon>
        <bal-list-item-icon right>
            <bal-icon name="nav-go-right" size="small"></bal-icon>
        </bal-list-item-icon>
    </bal-list-item>
</bal-list>
```

**Comment by fabio-tedesco** [comment]
hello @hirsch88 I'm not sure where that screenshot comes from, because in Figma in Online Training Chapter we have the star icon directly after the text. 
The source code from above renders the second icon on the right side just close to the arrow icon on the right side, or am I wrong?

Because this is what we'd need instead: the second icon on the right side directly after the content. Like here https://www.figma.com/file/FVkAs6sb8eBO18qmoXk7YX/%F0%9F%A4%B9%F0%9F%8F%BC%E2%80%8D%E2%99%82%EF%B8%8F-Baloise-Rebranding-Design-Kit?node-id=7975%3A189688&t=yWKREHBbfCTGrRQI-0 

About the icons themselves: I think we have the empty/filled star icons already, from the rating component. 

Please check the second icon position and in case we need the two icons on the right side close each other instead, like on the screenshot above, then the Figma should be updated and a designer should have a look and confirm first. Thanks in advance

**Comment by hirsch88** [comment]
Hi @fabio-tedesco @clastzoo will take care of that

**Comment by Gagne87** [comment]
Hi guys, following icons have to be uploaded to the DS:

![Image](https://user-images.githubusercontent.com/29020214/208877301-33ef5701-035c-4ba4-9b98-55a8feb9b27d.svg)
![Image](https://user-images.githubusercontent.com/29020214/208877302-93f8692d-93ee-4cd9-a46f-4e11da44c0c3.svg)

**Comment by Gagne87** [comment]
@clastzoo have not uploaded them to Frontify yet. Would like to discuss with you how we upload them as the icons are uploaded in black to Frontify, which is problematic for the grey version.
